[package]
name = "clockwork-handlebars"
version = "0.1.0"
authors = ["Layl <LaylConway@users.noreply.github.com>"]

[dependencies]
handlebars = {version = "0.18.2", features = ["serde_type"]}
serde = "^0.7.0"
serde_macros = "^0.7.0"
webapp = {path = "../webapp"}
clockwork = {path = "../clockwork"}
